#!/bin/bash

PID=$(cat ../catnip.pid 2> /dev/null)
if [ $? -eq 0 ]; then
  ps -p $PID > /dev/null 2>&1
  if [ $? -eq 0 ]; then
    echo "Process already running."
    exit
  fi
fi

function killChild {
  kill $PID
}

trap "killChild" SIGTERM

echo $$ > ../catnip.pid

COMMAND=$1
shift
while true; do
  $COMMAND "$@" &
  PID=$!
  echo $PID > ../process.pid
  wait $PID
  if [ $? -eq 143 ]; then
    echo "Process was stopped"
    rm -f ../catnip.pid
    exit
  fi
  echo "Process exited with code: $?"
  rm -f ../process.pid
  sleep 15
done