#!/bin/bash

PID=$(cat ../pid/catnip.pid 2> /dev/null)
if [ $? -eq 0 ]; then
  ps -p $PID > /dev/null 2>&1
  if [ $? -eq 0 ]; then
    echo "Process already running."
    exit
  fi
fi

function killChild {
  PID=$(cat ../pid/process.pid 2> /dev/null)
  if [ $? -eq 0 ]; then
    ps -p $PID > /dev/null 2>&1
    if [ $? -eq 0 ]; then
      kill $PID
    fi
  fi
}

trap "killChild" SIGTERM

echo $$ > ../pid/catnip.pid

COMMAND=$1
shift
while true; do
  $COMMAND "$@" &
  PID=$!
  echo $PID > ../pid/process.pid
  wait $PID
  STATUS=$?
  rm -f ../pid/process.pid
  if [ $STATUS -eq 143 ]; then
    echo "Process was stopped"
    rm -f ../pid/catnip.pid
    exit
  fi
  echo "Process exited with code: $STATUS"
  for i in {1..15}; do
    sleep 1
  done
done